'use strict';
const poseCleanups=[];
function disposePoseViewers(){poseCleanups.splice(0).forEach(cleanup=>cleanup());}
function attachPoseViewer(parent,row,run){
  const section=node('section',null,'pose-section'),heading=node('h4','Predicted ligand pose · Boltz-2'),controls=node('div',null,'pose-controls'),status=node('p','Load the saved coordinates to explore this candidate in 3D.','field-note'),canvas=node('div',null,'pose-canvas');
  canvas.hidden=true;canvas.setAttribute('role','img');canvas.setAttribute('aria-label','Interactive predicted protein–ligand structure for '+row.compound_id);
  const structures=row.discovery_result.structures,select=node('select');select.setAttribute('aria-label','Pose artifact for '+row.compound_id);structures.forEach((a,i)=>{const option=node('option','Pose '+(i+1)+' · '+a.format);option.value=String(i);select.append(option);});
  const load=node('button','View 3D pose','primary'),reset=node('button','Fit complex','secondary'),focus=node('button','Focus ligand','secondary'),label=node('label',null,'check-line'),protein=node('input');protein.type='checkbox';protein.checked=true;label.append(protein,node('span','Show protein'));[reset,focus,protein].forEach(e=>e.disabled=true);
  controls.append(select,load,reset,focus,label);section.append(heading,controls,status,canvas,node('p','Drag to rotate · Scroll or pinch to zoom. Protein: blue · Ligand: element-colored sticks. Coordinates are predicted, not experimental. Displayed bonds are inferred for visualization; pose atoms are not mapped to DILI attributions.','field-note'));
  if(!run){load.hidden=true;const fileLabel=node('label','Load matching structure file (local only)'),file=node('input');file.type='file';file.accept='.cif,.mmcif,.pdb,.sdf,.mol';fileLabel.append(file);section.append(fileLabel);file.onchange=async()=>{const value=file.files[0];if(!value)return;await readPose(async()=>{if(value.size>10000000)throw new Error('size');const bytes=await value.arrayBuffer(),digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(b=>b.toString(16).padStart(2,'0')).join('');if(digest!==structures[Number(select.value)].sha256)throw new Error('checksum');return {content:new TextDecoder().decode(bytes),format:structures[Number(select.value)].format};});};}
  let viewer=null,model=null,ligand=null,revision=0,dead=false;
  const observer=new ResizeObserver(()=>{if(viewer&&!canvas.hidden){viewer.resize();viewer.render();}});observer.observe(canvas);
  const cleanup=()=>{dead=true;revision++;observer.disconnect();if(viewer){viewer.removeAllModels();viewer.clear();}canvas.replaceChildren();viewer=null;};poseCleanups.push(cleanup);
  function style(){viewer.setStyle({},{});if(protein.checked)viewer.setStyle({hetflag:false},{cartoon:{color:'#809bb8',opacity:.75}});viewer.setStyle(ligand,{stick:{radius:.19,colorscheme:'orangeCarbon'},sphere:{scale:.23,colorscheme:'orangeCarbon'}});viewer.render();}
  async function readPose(read){const current=++revision;load.disabled=true;status.textContent='Verifying and loading saved coordinates…';try{const data=await read();if(dead||current!==revision)return;if(!['mmcif','cif','pdb','sdf','mol'].includes(data.format))throw new Error('format');canvas.hidden=false;if(!viewer)viewer=$3Dmol.createViewer(canvas,{backgroundColor:'#f0f3f7',antialias:true});viewer.removeAllModels();model=viewer.addModel(data.content,data.format==='mmcif'?'cif':data.format==='mol'?'sdf':data.format);const atoms=model.selectedAtoms({});if(!atoms.length||!atoms.every(a=>Number.isFinite(a.x)&&Number.isFinite(a.y)&&Number.isFinite(a.z)))throw new Error('coordinates');const ligands=['sdf','mol'].includes(data.format)?atoms:atoms.filter(a=>a.hetflag&&!['HOH','WAT'].includes(a.resn));if(!ligands.length)throw new Error('ligand');ligand={index:ligands.map(a=>a.index)};protein.checked=true;style();viewer.zoomTo();viewer.render();[reset,focus,protein].forEach(e=>e.disabled=false);status.textContent=row.compound_id+' · '+ligands.length+' ligand atoms · '+atoms.length+' total atoms · Verified saved coordinates.';}catch{if(dead||current!==revision)return;canvas.hidden=true;if(viewer)viewer.removeAllModels();[reset,focus,protein].forEach(e=>e.disabled=true);status.textContent='The saved pose could not be displayed. Check that the artifact exists and matches its recorded checksum, and that WebGL is enabled. No replacement pose was generated.';}finally{if(!dead&&current===revision)load.disabled=false;}}
  load.onclick=()=>readPose(()=>resultsSource.structure({job_id:run?.job_id,source:run?.mode==='recorded'?'recorded':undefined,compound_id:row.compound_id,index:Number(select.value)}));
  select.onchange=()=>{revision++;load.disabled=false;canvas.hidden=true;if(viewer)viewer.removeAllModels();[reset,focus,protein].forEach(e=>e.disabled=true);status.textContent='Load the selected artifact to view its saved pose.';};
  reset.onclick=()=>{viewer.zoomTo();viewer.render();};focus.onclick=()=>{viewer.zoomTo(ligand);viewer.render();};protein.onchange=style;
  parent.append(section);
}
